services:
  django-heroes:
    build:
      context: .
      dockerfile: Dockerfile
    image: xedose/django_heroes:latest
    container_name: django_heroes
    ports:
      - "80:8000"
    environment:
      - DEBUG=True
      - PYTHONUNBUFFERED=1